import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../tailwind/tailwind.output.css";
import { NavigationBar } from "@/components/layout/navigation-bar";
import { Footer } from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <head>
        {/* <link rel="icon" type="image/svg+xml" href="/favicon.svg" /> */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicon/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <title>Lecca.io - AI Agents and Workflow Automation</title>
        <meta
          name="description"
          content={
            "We provide software that allows businesses to create AI Agents and Workflow Automations."
          }
        />
      </head>
      <body className={`${inter.className}`}>
        <NavigationBar />
        {children}
        <Footer />

        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
                document.body.classList.add("dark");
              } else {
                document.body.classList.remove("dark");
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
